# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mY0D1oEqU1nyNmToL3y5ZJbxnynEBj8z

Task 1: Transparency in Algorithm Optimization
Naive Prime Checking Approach
"""

def is_prime_naive(n):
    """
    Checks if a number is prime using a basic approach.
    """
    if n <= 1:
        return False

    for i in range(2, n):
        if n % i == 0:
            return False
    return True

"""Optimized Prime Checking Approach"""

import math

def is_prime_optimized(n):
    """
    Checks if a number is prime using an optimized approach.
    """
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False

    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False
    return True

"""Task 2: Transparency in Recursive Algorithms (Fibonacci)
Recursive Fibonacci Function (Well-Commented)
"""

def fibonacci(n):
    """
    Recursively calculates the nth Fibonacci number.
    """

    # Base case 1: Fibonacci of 0 is 0
    if n == 0:
        return 0

    # Base case 2: Fibonacci of 1 is 1
    if n == 1:
        return 1

    # Recursive call:
    # The function calls itself with smaller values of n
    return fibonacci(n - 1) + fibonacci(n - 2)

"""Verification with Execution"""

fibonacci(4)
# → fibonacci(3) + fibonacci(2)
# → (fibonacci(2) + fibonacci(1)) + (fibonacci(1) + fibonacci(0))
# → (1 + 1) + (1 + 0)
# → 3

"""Task 3: Transparency in Error Handling
Python Program with Proper Error Handling
"""

def read_and_process_file(filename):
    try:
        # Attempt to open and read the file
        with open(filename, 'r') as file:
            data = file.read()
            print("File content length:", len(data))

    except FileNotFoundError:
        # Raised when the file does not exist
        print("Error: The file was not found.")

    except PermissionError:
        # Raised when the program lacks permission to read the file
        print("Error: Permission denied while accessing the file.")

    except Exception as e:
        # Catches unexpected errors
        print("An unexpected error occurred:", str(e))

    else:
        # Runs if no exception occurs
        print("File processed successfully.")

    finally:
        # Always executes
        print("File operation attempt completed.")

"""Revised Secure Authentication System"""

import hashlib

users = {}

def hash_password(password):
    """
    Hashes a password using SHA-256.
    """
    return hashlib.sha256(password.encode()).hexdigest()

def register(username, password):
    if not username or not password:
        print("Invalid input.")
        return
    users[username] = hash_password(password)

def login(username, password):
    if username in users:
        if users[username] == hash_password(password):
            print("Login successful.")
        else:
            print("Incorrect password.")
    else:
        print("User not found.")

"""Improved Privacy-Aware Logging"""

import logging
from datetime import datetime

logging.basicConfig(filename="activity.log", level=logging.INFO)

def log_activity(user_id):
    """
    Logs minimal, anonymized user activity.
    """
    timestamp = datetime.now().isoformat()
    logging.info(f"UserID={user_id} accessed system at {timestamp}")